export const GITHUB_SEARCH_ISSUES_LIST_INIT = '[GITHUB_ISSUES] GITHUB_SEARCH_ISSUES_LIST_INIT';
export const GITHUB_SEARCH_ISSUES_LIST_SUCCESS = '[GITHUB_ISSUES] GITHUB_SEARCH_ISSUES_LIST_SUCCESS';
export const GITHUB_SEARCH_ISSUES_LIST_ERROR = '[GITHUB_ISSUES] GITHUB_SEARCH_ISSUES_LIST_ERROR';
